Repository Qiskit/qiskit.org, pull requests merged in 2019-06, with the labels that each got.

#147 IBM Q Community page
  data/codeofconduct.pdf
  images/community/advocates.jpg
  images/community/commlogo.png
  images/community/europe.jpg
  images/community/qiskitBlack.jpg
  images/community/qiskitcamps.jpg
  images/community/qiskitcamps2.jpg
  src/components/app-shell.js
  src/components/page-community.js
  src/router.js
Labels: type: feature request

#148 Introduce static community event pages
  .gitignore
  community-src/collections/events/europe.md
  community-src/collections/events/img/madrid-bg-hi-res.jpg
  community-src/collections/events/img/madrid-bg-low-res.jpg
  community-src/collections/events/style/qiskit-camp.css
  community-src/layouts/qiskit-camp.hbs
  gulpfile.js
  metalsmith.js
  package-lock.json
  package.json
Labels: type: feature request

#149 Minor fixes
  community-src/collections/events/img/madrid-bg-hi-res.jpg
  community-src/collections/events/img/madrid-bg-low-res.jpg
  images/community/advocates.jpg
  images/community/commlogo.png
  images/community/europe.jpg
  images/community/qiskitBlack.jpg
  images/community/qiskitcamps.jpg
  images/community/qiskitcamps2.jpg
  locales/de/app.json
  locales/en/app.json
  src/components/app-shell.js
  src/helpers/track-events.js
Labels: type: bug

#151 Copy updates on Community Page
  src/components/page-community.js
Labels: type: enhancement

#155 Add milestones in analytics code
  src/components/app-shell.js
  src/helpers/track-events.js
Labels: type: feature request
