Repository Qiskit/qiskit.org, pull requests merged in 2019-05, with the labels that each got.

#119 Update copy with Qiskit 0.9 news
  gulpfile.js
  locales/de/app.json
  locales/en/app.json
  src/components/page-home.js
Labels: type: feature request

#124 change tutorials link
  src/components/app-shell.js
Labels: type: bug

#126 change tutorials broken link on offcanvas menu
  src/components/app-shell.js
Labels: type: bug

#128 Segment Analytics: Remove page track code
  gulpfile.js
  src/components/app-shell.js
Labels: type: feature request

#135 Feature: Track events by Analytics
  gulpfile.js
  index.html
  src/components/app-shell.js
  src/components/page-aer.js
  src/components/page-aqua.js
  src/components/page-fun.js
  src/components/page-home.js
  src/components/page-ignis.js
  src/components/page-terra.js
  src/components/page-vscode.js
  src/helpers/track-events.js
Labels: type: feature request

#136 Update qiskit notebooks section
  images/ibm-q-experience-2.jpg
  images/qiskit-notebooks.jpg
  locales/de/app.json
  locales/en/app.json
  src/components/page-home.js
Labels: type: enhancement

#139 update Aqua's set of algorithms
  src/components/page-aqua.js
Labels: type: feature request
