Repository Qiskit/qiskit.org, pull requests merged in 2023-06, with the labels that each got.

#3310 feat(qgss23): disable registration CTA
  constants/summerSchool2023Content.ts
  pages/events/summer-school-2023.vue
Labels: feature

#3367 feat(ecosystem-item-card): update alignment
  components/Ecosystem/EcosystemItemCard.vue
Labels: bug

#3376 Reactivate Registration button in QGSS 2023
  constants/summerSchool2023Content.ts
  pages/events/summer-school-2023.vue
Labels: ON HOLD
